# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

event_writer <- function(file) {
    .Call(`_tensorboard_event_writer`, file)
}

flush_event_writer <- function(writer) {
    invisible(.Call(`_tensorboard_flush_event_writer`, writer))
}

write_scalar <- function(writer, name, data, step, description) {
    .Call(`_tensorboard_write_scalar`, writer, name, data, step, description)
}

